### ISSUE TITLE
Segfault on CentOS 6 x86_64

### ISSUE THREAD

**Issue by davewkzn** [zevenet/packetbl#2]
Hi,

I managed to compile packetbl on CentOS 6 x86_64 by installing appropriate packages, and also adjusted the following in the 'configure' script:
NF_VERSION=`rpm -q libnetfilter_queue-devel | awk -F'-devel-' '{print $2}' | cut -d. -f1`

Unfortunately packetbl segfaults as soon as traffic is passed to it - please see the syslog entries as follows:

Oct 30 20:23:42 xxxxx packetbl[19428]: Error reading packet. Accepting packet.
Oct 30 20:23:42 xxxxx kernel: packetbl[19429]: segfault at d8 ip 00007fe28c35e6df sp 00007fe28ba84d80 error 6 in libc-2.12.so[7fe28c295000+18a000]
Oct 30 20:23:42 xxxxx kernel: packetbl[19430]: segfault at d8 ip 00007fe28c35e6df sp 00007fe28b083d80 error 6 in libc-2.12.so[7fe28c295000+18a000]

Have you come across this before?

**Comment by alvarocano-zevenet** [comment]
Hi Davewkzn,

Unfortunately packetbl has not been tested in centOS. It is developed for Debian Jessie and Debian Stretch as the documentation specifies.

To make compatible packetbl with centOS, it would have to do a development, if you want to give support to centOS are welcome to the project!

**Comment by computersalat** [comment]
@alvarocano-zevenet 
sorry, but never heard such a **bullshit**
better test your code with different version of libs you are using ...
... and provide an **exact dependency for the lib versions**. Then it should not be a problem to make it run on different linux.
Improve your code not to write to **protected** memory then it will not segfault

**Comment by nevola** [comment]
@computersalat thank you for your wonderful comment. I'm sure that you put all it takes to elaborate it thoroughly.
As @alvarocano-zevenet said, we tested it with several Debian releases, if you want to know the exact versions, go to the repository and check them out as these versions are not fixed. And no, we are not able to test with several libraries that we do not use and we never going to.
If you're for any chance interested in us to fix anything, please provide something more than your opinions, for example, an gdb trace.
