### ISSUE TITLE
Debian 9 make error

### ISSUE THREAD

**Issue by bcacbe** [zevenet/packetbl#4]
I'm seeing the following error on make, not sure how to continue. Any help is appreciated.

`root@deb2:~/packetbl/src# make
gcc -g -O2   packetbl.o -o ../bin/packetbl -lpool -ldotconf -lldns -lpthread  -lnetfilter_queue -lnfnetlink
/usr/bin/ld: cannot open output file ../bin/packetbl: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'packetbl' failed
make: *** [packetbl] Error 1`

**Comment by alvarocano-zevenet** [comment]
Hello @bcacbe,

It looks like the makefile could not find the "bin" directory, could you create the "bin" directory in the root of the repository and test to compile again? 

You only should execute:
```
mkdir ~/packetbl/bin
cd  ~/packetbl/src
make clean; make
```

Please, confirm to us if this solves the issue.
Best regards
